config/routes.rb
StoneyPoint::Application.routes.draw do
  devise_for :users
  resources :organizations
  resources :users, only: [:index, :update]

  resources :work_days

  resources :housings do
    member do
      post "/waiver_check", to: "housings#waiver_check"
    end
  end

  resources :caddies

  resources :golfers do
    member do
      post "/waiver_check", to: "golfers#waiver_check"
    end
  end

  resources :jobs

  resources :shifts

  get "/volunteers", to: "committees#index"

  resources :committees do
    collection do
      get "show_all_schedules", to: "committees#show_all_schedules"
      get "show_day", to: "committees#show_day"
    end
    member do
      get "show_schedule", to: "committees#show_schedule"
    end
  end

  resources :volunteers do
    member do
      put "/check_in", to: "volunteers#check_in"
    end
  end

  get "jr_clinic_day", to: "volunteers#jr_clinic_day"
  get "/volunteer_addresses", to: "volunteers#addresses"
  post "/update_shirt_paid", to: "volunteers#update_shirt_paid"

  get "/people/links", to: "people#links", as: 'links'

  resources :people

  get "/welcome_volunteers/welcome", to: "welcome_volunteers#welcome"

  get "/welcome_volunteers/returning", to: "welcome_volunteers#returning"
  post "/welcome_volunteers/find", to: "welcome_volunteers#find"
  get "/welcome_volunteers/thank_you", to: "welcome_volunteers#thank_you"

  get "/welcome_housing/returning", to: "welcome_housing#returning"
  post "/welcome_housing/find", to: "welcome_housing#find"

  get "/welcome_caddies/returning", to: "welcome_caddies#returning"
  post "/welcome_caddies/find", to: "welcome_caddies#find"

  resources :welcome_volunteers, except: [:index, :show]
  resources :welcome_housing, except: [:index, :show]

  get "/welcome_caddies/thank_you", to: "welcome_caddies#thank_you"
  resources :welcome_caddies, except: [:index, :show]

  post "/add_volunteer_committee", to: "volunteers#add_committee", as: 'add_volunteer_committee'
  post "/add_volunteer_job", to: "volunteers#add_job", as: 'add_volunteer_job'
  post "/add_volunteer_shift", to: "volunteers#add_shift", as: 'add_volunteer_shift'
  post "/duplicate_volunteer", to: "volunteers#duplicate", as: 'duplicate_volunteer'
  post "/add_golfer_caddie", to: "golfers#add_caddie", as: 'add_golfer_caddie'
  post "/add_volunteer_organization", to: "volunteers#add_organization", as: 'add_volunteer_organization'
  post "/add_caddie_organization", to: "caddies#add_organization", as: 'add_caddie_organization'
  post "/add_volunteer_housing", to: "volunteers#add_housing", as: 'add_volunteer_housing'
  post "/add_golfer_to_housing", to: "housings#add_golfer", as: 'add_golfer_to_housing'

  get "/shirts", to: "volunteers#shirts", as: 'shirts'

  root :to => 'committees#index'

end

app/controllers/caddies_controller.rb
class CaddiesController < ApplicationController
  before_action :set_caddie, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, only: [:index, :show, :shirts]
  skip_before_filter :permit_only_admin, only: [:index, :show, :shirts]

  def index
    if params[:show_all] == 'true'
      @caddies = Caddie.by_last_name.includes(:person)
    else
      @caddies = Caddie.active.by_last_name.includes(:person)
    end
  end

  def show
  end

  def new
    @person_form = PersonForm.new(
      person: Person.find_by_id(params[:person_id])
    )
  end

  def edit
    @person = @caddie.person
    @person_form = PersonForm.new(
      page_params: params,
      caddie:      @caddie,
      person:      @person
    )
  end

  def create
    @caddie = Caddie.new
    @person = Person.find_by_id(params[:person_id]) || Person.new
    @person_form = PersonForm.new(
      page_params: params,
      caddie:      @caddie,
      person:      @person
    )

    if @person_form.update
      redirect_to :back, notice: 'Caddie was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @person = @caddie.person
    @person_form = PersonForm.new(
      page_params: params,
      caddie:      @caddie,
      person:      @person
    )
    if @person_form.update
       redirect_to @caddie, notice: 'Caddie was successfully updated.'
    else
       render action: 'edit'
    end
  end

  def destroy
    @caddie.destroy
    redirect_to :back
  end

  def add_organization
    organization_id = params[:caddie][:organization_id]
    @caddie = Caddie.find(association_params[:id])
    if @caddie.person.update_attributes(:organization_id => organization_id )
      redirect_to :back, notice: "#{@caddie.full_name}'s organization was updated."
    else
      redirect_to :back, notice: "We're sorry, an error has occurred. Please try again."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caddie
      @caddie = Caddie.find(params[:id])
    end

    def association_params
      params.require(:caddie).permit(:id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caddie_params
      params.require(:caddie).permit(:first_name, :last_name, :phone, :email, :comments, :golf, :rules, :course, :is_active)
    end
end

app/helpers/caddies_helper.rb
module CaddiesHelper

  def golfer_label
    public_facing_page? ? "Are you a golfer?" : "Do they golf?"
  end

  def caddie_experience
    public_facing_page? ? "Have you caddied before?" : "Caddie experience?"
  end

  def age
    public_facing_page? ? "What is your age?" : "Age"
  end

  def know_the_course
    public_facing_page? ? "Rate your knowledge of the golf course" : "Course?"
  end

  def know_the_rules
    public_facing_page? ? "Rate your knowlege of the rules" : "Rules?"
  end

  def caddie_waiver_text
    display_waiver? ? "I am at least 18 years of age and I accept these terms and conditions" : "Accepted waiver"
  end

end

app/views/caddies/_form.html.slim
= f.fields_for @person_form.caddie do |caddie|
  .row
    .col-md-12
      hr
      h3 Knowledge and Skills
    .col-xs-6
      .form-group
        .checkbox
          = caddie.label :golf do
            = caddie.check_box :golf
            = golfer_label
    .col-xs-6
      .form-group
        .checkbox
          = caddie.label :experience_as_caddie do
            = caddie.check_box :experience_as_caddie
            = caddie_experience
    .col-xs-6
      .form-group
        = caddie.label know_the_course
        = caddie.select :course, Caddie::KNOWLEDGE_OPTIONS, { include_blank: true, prompt: "Choose one..." }, class: "form-control chosen-select"
    .col-xs-6
      .form-group
        = caddie.label know_the_rules
        = caddie.select :rules, Caddie::KNOWLEDGE_OPTIONS, { include_blank: true, prompt: "Choose one..." }, class: "form-control chosen-select"
    .col-xs-6
      .form-group
        = caddie.label age
        = caddie.number_field :age, class: "form-control"
  .row
    .col-md-12
      hr
    .col-xs-12
      .form-group
        = caddie.label :comments
        = caddie.text_area :comments, class: 'form-control'
  .row
    hr
  .row
    - if display_waiver?
      .col-xs-12
        h4 Waiver
      .col-xs-12.js-show-more
        .well.show-more.truncate
          h4 Volunteer Disclosure, Waiver and Release Statement
          em It is most important that you read the following before signing.
          p I understand that:
          ul
            li In the course of volunteering for the Self Regional Healthcare Foundation Women's Health Charity Classic ("Tournament"), I may be dealing with confidential information and I agree to keep such information in the strictest confidence.
            li The relationship between the "Tournament" and volunteers may be discontinued at any time by either the volunteer or the "Tournament."
            li I understand and acknowledge that I am strictly a volunteer, not an employee of the "Tournament"; that I volunteer my services freely and without pressure or coercion, direct or implied, from the "Tournament"; and, that there has been no promise of nor do I have an expectation of receiving compensation for the volunteer labor I may provide.
            li I grant the "Tournament" permission throughout the universe to use my likeness, voice, and words in television, radio, pictures, videotapes, film or any other form now known or hereinafter devised to promote activities of the "Tournament" without compensation.
            li I assume all risks surrounding and associated with my participation in activities and events organized and sponsored by the "Tournament", including injury, death, or illness to me and/or damage to or loss of my or others' property, whether caused by the negligence of Releasees, as defined below, or otherwise.  In consideration for allowing me to participate as a volunteer for the "Tournament" and all other benefits to me arising therefrom, I hereby waive, release, covenant not to sue, and forever discharge the "Tournament", Ladies Professional Golf Association, Symetra Life Insurance Company, The Self Regional Healthcare Foundation, The Links at Stoney Point (Hole 19 LLC),  The Stoney Point Property Owners Association and all other persons and entities, including but not limited to, sponsors, agencies, corporations, associates, staff, volunteers, providers of first aid and independent contractors liable or who might be claimed to be liable (collectively, “Releasees”) from any and all claims, actions, liabilities, and causes of action, whether involving negligence or intentional acts or omissions, which I and/or any of my heirs, successors, executors, administrators, agents or assigns may now have or which may accrue as a result of or in connection with my volunteering for the "Tournament".  I further agree to indemnify, defend and hold harmless the Releasees for any liability, demand, judgment, claim or suit, including reasonable costs and attorney fees, arising out of or in connection with my acts or omissions or allegations thereof as a volunteer for the "Tournament."
            li In the event that I am unable to do so on my own because of injury or illness, I consent to administration of first aid and/or medical treatment, and agree to indemnify, waive, release, covenant not to sue, and forever discharge Releasees from any and all liability or claims arising out of such treatment.
            li I understand that the nature of the "Tournament" and the participating athletes make it necessary to have in place a screening process for all volunteers.  My signature on this Volunteer Waiver and Release Statement shall serve as authorization to perform a criminal history record information check in connection with my volunteer application for the "Tournament."
            li I, a volunteer for the "Tournament", hereby attest that I have never been found guilty of, or entered a plea of guilty or of nolo contendere (i.e., no contest) to a crime determined to be a misdemeanor or felony.  I further attest that I have never been judicially determined to have committed abuse or neglect against a person, child, or animal. Under penalty of perjury, I hereby declare that the attestations above are true to the best of my knowledge and belief.

        a.pull-right.btn.btn-default.btn-xs.js-more-btn Read More
    .col-xs-12
      .form-group
        .checkbox
          = caddie.label :waiver do
            = caddie.check_box :waiver, class: 'js-i-accept'
            = caddie_waiver_text

app/views/caddies/_show.html.slim
.well
  .row
    .col-xs-3
      h5 Knowledge of Golf?
      p = caddie.golf ? "Yes" : "No"

    .col-xs-3
      h5 Knowledge of the Course?
      p = caddie.course

    .col-xs-3
      h5 Knowledge of the Rules?
      p = caddie.rules

    .col-xs-3
      h5 Experience as a Caddie?
      p = caddie.experience_as_caddie ? "Yes" : "No"
  .row
    .col-xs-4
      h5 Age
      p = caddie.age

    .col-xs-4
      h5 Waiver signed?
      p = caddie.waiver ? "Yes" : "No"

  .row
    .col-xs-12
      h5 Comments:
      p = caddie.comments

  - if caddie.golfer.present?
    .row
      .col-xs-3
        h5 Golfer
        p = link_to caddie.golfer.full_name, caddie.golfer

app/views/caddies/edit.html.slim
h1 Editing caddie
.row
  .col-xs-12
    = form_for(@person_form, url: caddie_url, method: :patch, html: {class: 'form-vertical' }) do |f|
      = render partial: 'people/form', locals: { f: f }
      = render partial: 'form', locals: { f: f }
      .form-group
        = f.label :organization,  for: "person_form_person_organization_id"
        = select_tag :organization,
          options_from_collection_for_select(Organization.all, "id", "name", selected: @person_form.person.organization),
          include_blank: true,
          class: "form-control chosen-select",
          id: "person_form_person_organization_id",
          name: "person_form[person_organization_id]"

      .form_actions
        = f.button :save, class: 'btn btn-primary'

.row
  .col-xs-12
    = link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, @caddie, :class => 'btn btn-small'
    = link_to '<span class="glyphicon glyphicon-list"></span>'.html_safe, caddies_path, :class => 'btn btn-small'

app/views/caddies/index.html.slim
h1 Caddies
- if current_user.try(:admin?)
  = link_to 'New Caddie', new_caddie_path
  '  |
  = link_to 'Show all', :show_all => true
hr
table.table.table-striped#data_table
  thead
    tr
      th Last
      th First
      th Know Golf?
      th Know the Course?
      th Know the Rules?
      th Exp
      th Age
      th Comments
      th
      - if current_user.try(:admin?)
        th
        th

  tbody
    - @caddies.each do |caddie|
      tr
        td = link_to caddie.last_name, caddie
        td = link_to caddie.first_name, caddie
        td = caddie.golf ? 'Yes' : 'No'
        td = caddie.course
        td = caddie.rules
        td = caddie.experience_as_caddie ? "Yes" : "No"
        td = caddie.age
        td = caddie.comments
        td = link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, caddie, :class => 'btn btn-small'
        - if current_user.try(:admin?)
          td = link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_caddie_path(caddie), :class => 'btn btn-small'
          td = link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, caddie, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-small'

= render 'shared/datatable_js'

app/views/caddies/new.html.slim
.row
  .col-xs-12
    h1
      ' New Caddie
.row
  .col-xs-12
    = form_for(@person_form, url: caddies_url, method: :post, html: {class: 'form-vertical' }) do |f|
      = render partial: 'people/form', locals: {f: f}
      = render partial: "form", locals: { f: f, person_form: @person_form }
      = hidden_field_tag "return_to", "caddie"
      .form-group
        = f.label :organization,  for: "person_form_person_organization_id"
        = select_tag :organization,
          options_from_collection_for_select(Organization.all, "id", "name", selected: @person_form.person.organization),
          include_blank: true,
          class: "form-control",
          id: "person_form_person_organization_id",
          name: "person_form[person_organization_id]"

      form-actions
        = f.button "Save", :class => 'btn btn-primary btn-large'

app/views/caddies/show.html.slim
= render partial: "people/show", locals: { person: @caddie.person, edit_path: edit_caddie_path(@caddie) }
= render partial: "show", locals: { caddie: @caddie }