config/routes.rb
StoneyPoint::Application.routes.draw do
  devise_for :users
  resources :organizations
  resources :users, only: [:index, :update]

  resources :work_days

  resources :housings do
    member do
      post "/waiver_check", to: "housings#waiver_check"
    end
  end

  resources :caddies

  resources :golfers do
    member do
      post "/waiver_check", to: "golfers#waiver_check"
    end
  end

  resources :jobs

  resources :shifts

  get "/volunteers", to: "committees#index"

  resources :committees do
    collection do
      get "show_all_schedules", to: "committees#show_all_schedules"
      get "show_day", to: "committees#show_day"
    end
    member do
      get "show_schedule", to: "committees#show_schedule"
    end
  end

  resources :volunteers do
    member do
      put "/check_in", to: "volunteers#check_in"
    end
  end

  get "jr_clinic_day", to: "volunteers#jr_clinic_day"
  get "/volunteer_addresses", to: "volunteers#addresses"
  post "/update_shirt_paid", to: "volunteers#update_shirt_paid"

  get "/people/links", to: "people#links", as: 'links'

  resources :people

  get "/welcome_volunteers/welcome", to: "welcome_volunteers#welcome"

  get "/welcome_volunteers/returning", to: "welcome_volunteers#returning"
  post "/welcome_volunteers/find", to: "welcome_volunteers#find"
  get "/welcome_volunteers/thank_you", to: "welcome_volunteers#thank_you"

  get "/welcome_housing/returning", to: "welcome_housing#returning"
  post "/welcome_housing/find", to: "welcome_housing#find"

  get "/welcome_caddies/returning", to: "welcome_caddies#returning"
  post "/welcome_caddies/find", to: "welcome_caddies#find"

  resources :welcome_volunteers, except: [:index, :show]
  resources :welcome_housing, except: [:index, :show]

  get "/welcome_caddies/thank_you", to: "welcome_caddies#thank_you"
  resources :welcome_caddies, except: [:index, :show]

  post "/add_volunteer_committee", to: "volunteers#add_committee", as: 'add_volunteer_committee'
  post "/add_volunteer_job", to: "volunteers#add_job", as: 'add_volunteer_job'
  post "/add_volunteer_shift", to: "volunteers#add_shift", as: 'add_volunteer_shift'
  post "/duplicate_volunteer", to: "volunteers#duplicate", as: 'duplicate_volunteer'
  post "/add_golfer_caddie", to: "golfers#add_caddie", as: 'add_golfer_caddie'
  post "/add_volunteer_organization", to: "volunteers#add_organization", as: 'add_volunteer_organization'
  post "/add_caddie_organization", to: "caddies#add_organization", as: 'add_caddie_organization'
  post "/add_volunteer_housing", to: "volunteers#add_housing", as: 'add_volunteer_housing'
  post "/add_golfer_to_housing", to: "housings#add_golfer", as: 'add_golfer_to_housing'

  get "/shirts", to: "volunteers#shirts", as: 'shirts'

  root :to => 'committees#index'

end

app/controllers/welcome_housing_controller.rb
class WelcomeHousingController < ApplicationController
  skip_before_filter :permit_only_admin
  skip_before_filter :authenticate_user!
  layout "public"

  def new
    @person_form = PersonForm.new()
  end

  def find
    @attempt = params[:attempt].to_i
    # Case insensitive search
    t = Person.arel_table
    @first_name = search_params[:first_name].strip
    @last_name  = search_params[:last_name].strip
    @person = Person.where(t[:first_name].matches(@first_name).and(t[:last_name].matches(@last_name))).last

    if @person
      redirect_to edit_welcome_housing_path(@person)
    else
      @attempt += 1
      render action: 'returning'
    end
  end

  def welcome
  end

  def returning
    @attempt ||= 0
  end

  def create
    params[:person_form][:person_is_active] = true
    params[:person_form][:housing][:is_active] = true

    @person_form = PersonForm.new(
      page_params: params
    )
    if @person_form.update
      render action: 'thank_you'
    else
      render action: 'new', notice: "First and Last name are required. Please try again."
    end
  end

  def edit
    @person = Person.find(params[:id])
    @housing = @person.housings.first
    @person_form = PersonForm.new(
      page_params: params,
      housing:     @housing,
      person:      @person
    )
  end

  def update
    params[:person_form][:person_is_active] = true
    params[:person_form][:housing][:is_active] = true

    @person    = Person.find(params[:id])
    @housing   = @person.housings.first

    @person_form = PersonForm.new(
      page_params: { person_form: person_params },
      housing:     @housing,
      person:      @person
    )
    if @person_form.update
      render :thank_you
    else
      render action: 'edit', notice: "There was a problem saving."
    end
  end

  def thank_you
    render layout: "public"
  end

  private
  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    if params[:person_form].present?
      params.require(:person_form).permit(
        :person_first_name,
        :person_last_name,
        :person_email,
        :person_street,
        :person_city,
        :person_state,
        :person_zip,
        :person_phone,
        :person_organization_id,
        :person_is_active,
        housing: [
          :number_of_bedrooms,
          :number_of_bathrooms,
          :max_guests,
          :pets,
          :available,
          :specific_golfers,
          :smoking,
          :comments,
          :is_active,
          :waiver,
          golfer_ids: [],
        ]
      )
    end
  end

  def search_params
    params.require(:search).permit(
      :first_name,
      :last_name
    )
  end
end

app/views/welcome_housing/_form.html.slim
  = hidden_field_tag :welcome, true
  = render partial: 'people/form', locals: { f: f }
  h3 Host House Information

  h4
    em LPGA rules require that a woman be the host
  p Each bedroom must have ready access to bathroom and laundry facilities. NO smoking.
  hr
  p
    small Note: fields with an astrisk (*) must be completed.
  = f.simple_fields_for(person_form.housing) do |housing|
    = render partial: 'housings/form', locals: { f: housing }

app/views/welcome_housing/edit.html.slim
.row.jumbotron.edit-header
  .col-md-12
.row
  .col-xs-12
    h1
      | Welcome back, #{@person.first_name}. Register to be a player host again for the
      |  2017 Self Regional Healthcare Foundation Women's Health Classic
    hr
.row
  .col-md-12
    h3 Personal Data
    p
      | Please review personal data previously entered. Type any new or corrected
      |  information into the boxes provided. Your telephone number and email
      |  address should be the ones that allow us to contact you directly so that
      |  we may forward vital information before and during the tournament.
.row
  .col-xs-12
      = form_for(@person_form, url: welcome_housing_url, method: :patch, html: {class: 'form-vertical' }) do |f|
        = render 'form', person_form: @person_form, f: f

        hr
        .row
          .col-xs-12
            form-actions
              = f.button "Save", :class => 'btn btn-primary btn-large'

app/views/welcome_housing/new.html.slim
.row.jumbotron.edit-header
  .col-md-12
    h1 Welcome!

.row
  .col-xs-12
    h1 Welcome to the volunteer site for the 2017 Self Regional Healthcare Foundation Women's Health Classic.
    hr

.row
  .col-xs-12
    = form_for(@person_form, url: welcome_housing_index_path, method: :post, html: {class: 'form-vertical' }) do |f|
      = render 'form',  f: f, person_form: @person_form

      hr
      .row
        .col-xs-12
          form-actions
            = f.button "Save", :class => 'btn btn-primary btn-large'

app/views/welcome_housing/new_housing.html.slim
.row
  .col-md-12
    h1 Welcome!
    p
      | On behalf of the Self Regional Healthcare Foundation, The Links at Stoney Point Ladies Golf
      |  Classic LLC, the Ladies Pro Golf Association, and the Symetra Tour – Thank You for volunteering your time
      |  to assist with a very important part of the Self Regional Healthcare Foundation Women's Health Charity
      |  Classic tournament, May 11 thru 14, 2017.
    br
    br
    br
.row
  .col-md-4.col-md-offset-2
    .well
      = fa_icon "search 4x", class: "text-muted pull-left"
      h4 Search
      p If you've volunteered with us in the past, please enter your first and last name to search for your account.
      .clearfix
      br
      = form_tag welcome_volunteers_find_path
        .form-group
          label for="first_name" First Name
          = text_field_tag "search[first_name]", nil, class: "form-control", placeholder: 'Enter your first name'
        .form-group
          label for="last_name" Last Name
          = text_field_tag "search[last_name]", nil, class: "form-control", placeholder: 'Enter your last name'
        = submit_tag :search, class: 'btn btn-primary pull-right'
      .clearfix
  .col-md-4
    .well
      = fa_icon "user-plus 4x", class: "text-muted pull-left"
      h4 New Volunteers
      p
        | Welcome! We're thrilled you're here. Please take a moment to register through our website so we can stay
        |  in touch. If you have any questions about volunteering, feel free to contact us at #{mail_to 'info@stoneypoint.com'}
      = link_to "#{fa_icon('pencil')} Register".html_safe, new_welcome_volunteer_path, class: 'btn btn-primary pull-right'
      .clearfix

app/views/welcome_housing/returning.html.slim
.row.jumbotron.returning-header
  .col-md-12
    h1 Welcome Back!
.row
  .col-md-12
    h3 Returning Housing Volunteers
    p
      | Having previously volunteered, your personal data is on file. At the end of this
      |  message you will be asked to sign in to your account to review and update your information for 2017.
    h3 Terms and Conditions
    p
      | To volunteer on-line, each host must be over 18 years of age.
      |  NOTE: LPGA rules require that a woman be the host.

.row
- if @attempt > 0
  .alert.alert-danger
    button.close type="button" data-dismiss="alert"
      span aria-hidden="true" &times;
      span.sr-only Close
    h3 Sorry #{@first_name} #{@last_name}
    | We were unable to match you with a housing record from previous years. You may take one of two actions:
    ol
      li Check your spelling or the possibility you used a different form of your name and please try again. OR
      li
        | Send us an email
        | &nbsp;
        = mail_to 'stoneypointvolunteer@gmail.com', "here", subject: 'Stoney Point Housing Volunteer  - Help finding my account', body: "I'm a returning volunteer and I've been unable to find my account. Please help me get this sorted out.\n\nHere is my information:\n\nFirst Name: \nLast Name:\nPhone number:\n\nThank you!", class: 'btn btn-default btn-xs'
        |  and submit your information to our helpdesk. You will be contacted by email about a solution.
    h4 Thank you for your patience.

.row.well
  .col-md-6
    = fa_icon "user 4x", class: "text-muted pull-left"
    h4 Login Instructions
    p
      | To login, enter your first name and last name in the spaces provided.
    .clearfix
  .col-md-6
    = form_tag welcome_housing_find_path
      .form-group
        label for="first_name" First Name
        = text_field_tag "search[first_name]", @first_name, class: "form-control", placeholder: 'Enter your first name'
      .form-group
        label for="last_name" Last Name
        = text_field_tag "search[last_name]", @last_name, class: "form-control", placeholder: 'Enter your last name'

      = submit_tag :Login, class: 'btn btn-primary pull-right'
    .clearfix

app/views/welcome_housing/thank_you.html.slim
.row
  .jumbotron
    = image_tag "stoney_point.jpg", class: 'center-block'
    br
    h2.center-block Thank you for volunteering your time and talents
    h2.center-block Your application has been sent to our database and the information saved.
    p.pull-right
      | - The Links at Stoney Point