config/routes.rb
StoneyPoint::Application.routes.draw do
  devise_for :users
  resources :organizations
  resources :users, only: [:index, :update]

  resources :work_days

  resources :housings do
    member do
      post "/waiver_check", to: "housings#waiver_check"
    end
  end

  resources :caddies

  resources :golfers do
    member do
      post "/waiver_check", to: "golfers#waiver_check"
    end
  end

  resources :jobs

  resources :shifts

  get "/volunteers", to: "committees#index"

  resources :committees do
    collection do
      get "show_all_schedules", to: "committees#show_all_schedules"
      get "show_day", to: "committees#show_day"
    end
    member do
      get "show_schedule", to: "committees#show_schedule"
    end
  end

  resources :volunteers do
    member do
      put "/check_in", to: "volunteers#check_in"
    end
  end

  get "jr_clinic_day", to: "volunteers#jr_clinic_day"
  get "/volunteer_addresses", to: "volunteers#addresses"
  post "/update_shirt_paid", to: "volunteers#update_shirt_paid"

  get "/people/links", to: "people#links", as: 'links'

  resources :people

  get "/welcome_volunteers/welcome", to: "welcome_volunteers#welcome"

  get "/welcome_volunteers/returning", to: "welcome_volunteers#returning"
  post "/welcome_volunteers/find", to: "welcome_volunteers#find"
  get "/welcome_volunteers/thank_you", to: "welcome_volunteers#thank_you"

  get "/welcome_housing/returning", to: "welcome_housing#returning"
  post "/welcome_housing/find", to: "welcome_housing#find"

  get "/welcome_caddies/returning", to: "welcome_caddies#returning"
  post "/welcome_caddies/find", to: "welcome_caddies#find"

  resources :welcome_volunteers, except: [:index, :show]
  resources :welcome_housing, except: [:index, :show]

  get "/welcome_caddies/thank_you", to: "welcome_caddies#thank_you"
  resources :welcome_caddies, except: [:index, :show]

  post "/add_volunteer_committee", to: "volunteers#add_committee", as: 'add_volunteer_committee'
  post "/add_volunteer_job", to: "volunteers#add_job", as: 'add_volunteer_job'
  post "/add_volunteer_shift", to: "volunteers#add_shift", as: 'add_volunteer_shift'
  post "/duplicate_volunteer", to: "volunteers#duplicate", as: 'duplicate_volunteer'
  post "/add_golfer_caddie", to: "golfers#add_caddie", as: 'add_golfer_caddie'
  post "/add_volunteer_organization", to: "volunteers#add_organization", as: 'add_volunteer_organization'
  post "/add_caddie_organization", to: "caddies#add_organization", as: 'add_caddie_organization'
  post "/add_volunteer_housing", to: "volunteers#add_housing", as: 'add_volunteer_housing'
  post "/add_golfer_to_housing", to: "housings#add_golfer", as: 'add_golfer_to_housing'

  get "/shirts", to: "volunteers#shirts", as: 'shirts'

  root :to => 'committees#index'

end

app/models/committee.rb
class Committee < ActiveRecord::Base
  has_and_belongs_to_many :volunteers
  validates :name, presence: true

  JUNIOR_CLINIC = "Junior Clinic"
  EXCLUDED_FROM_SCHEDULING = ['ProShop', JUNIOR_CLINIC]

  scope :scheduleable, -> {where.not(name: [PersonForm::DEFAULT_COMMITTEE_NAME,'Operations'])}
  scope :sorted, -> { order('name ASC') }
  scope :junior_clinic, -> { where(name: JUNIOR_CLINIC) }

end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_action :set_committee, only: [:show, :edit, :update, :destroy, :show_schedule]
  skip_before_filter :authenticate_user!, only: [:index, :show, :shirts, :show_all_schedules, :show_schedule, :show_day]
  skip_before_filter :permit_only_admin, only: [:index, :show, :shirts, :show_all_schedules, :show_schedule, :show_day]

  def index
    if params[:show_all] == 'true'
      @volunteers = Volunteer.all.includes(:committees, person: :organization)
    elsif params[:unassigned] == 'true'
      @volunteers = Volunteer.active.includes(:committees, person: :organization) - Volunteer.active.working.includes(:committees, person: :organization)
    else
      @volunteers = Volunteer.active.working.includes(:committees, person: :organization)
    end
  end

  def show
    if params[:show_all] == 'true'
      @volunteers = @committee.volunteers.includes(:committees, person: :organization)
    else
      @volunteers = @committee.volunteers.active.includes(:committees, person: :organization)
    end
  end

  def show_all_schedules
    @read_write = current_user.try(:admin?)
    @volunteers = Volunteer.with_scheduleable_committees.includes(:jobs, :committees, :person).active.uniq
    @days = ["thursday", "friday", "saturday", "sunday"]
    @job_options = Job.all.collect{ |j| { text: j.title, value: j.id } }
    render "show_schedule"
  end

  def show_schedule
    @read_write = current_user.try(:admin?) || current_user.try(:role) == "#{@committee.name.titlecase} Manager"
    @volunteers = @committee.volunteers.includes(:jobs, :committees, :person).active
    @job_options = Job.all.collect{ |j| { text: j.title, value: j.id } }
    @days = ["thursday", "friday", "saturday", "sunday"]
  end

  def show_day
    @read_write = current_user.try(:manage_committees?) || current_user.try(:volunteer_center_manager?)
    @day = params[:day]
    @committees = Committee.sorted.scheduleable
    @volunteers = Volunteer.with_scheduleable_committees.includes(:jobs, :committees, :person).active.schedule_for(@day).uniq
  end

  def new
    @committee = Committee.new
  end

  def edit
  end

  def create
    @committee = Committee.new(committee_params)
    if @committee.save
      redirect_to :back, notice: 'Committee was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @committee.update(committee_params)
       redirect_to @committee, notice: 'Committee was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @committee.destroy
    redirect_to committees_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_committee
      @committee = Committee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def committee_params
      params.require(:committee).permit(:name)
    end
end

app/views/committees/_form.html.erb
<%= simple_form_for(@committee) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/committees/_volunteers_table.html.slim
table#data_table.table.table-striped
  thead
    tr
      th Last
      th First
      th Email
      th Phone
      th Committee
      th Organization
      th Waiver
      th Golf
      th Phys
      th Comment

  tbody
    - @volunteers.each do |volunteer|
      tr
        td = link_to(volunteer.last_name, volunteer)
        td = link_to(volunteer.first_name, volunteer)
        td = mail_to volunteer.email, volunteer.email, :encode => "javascript"
        td = build_phone_number(volunteer.phone)
        - if current_user.try(:manage_committees?)
          td = editable(volunteer,
                        :committee_ids,
                        type: "select",
                        source: Committee.all.collect{ |c| { value: c.id, text: c.name } },
                        value: volunteer.committee_ids.to_json,
                        tpl: "<select multiple='multiple'>",
                        class: 'multiple-select',
                        )
        - else
          td = volunteer.committees.collect{ |g| link_to g.name, g }.join(' ').html_safe
        td = volunteer.organization.try(:name)
        td = volunteer.waiver ? 'Y' : 'N'
        td = volunteer.golfer ? "Y" : "N"
        td = volunteer.physical_activity ? "Y" : "N"
        td = volunteer.comments
= render 'shared/datatable_js'

javascript:
  StoneyPoint.InlineEditing.init()

app/views/committees/edit.html.erb
<h1>Editing committee</h1>

<%= render 'form' %>

<%= link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, @committee, :class => 'btn btn-small' %>
<%= link_to '<span class="glyphicon glyphicon-list"></span>'.html_safe, committees_path, :class => 'btn btn-small' %>

app/views/committees/index.html.slim
h1
  | Volunteer Contact Information
  | &nbsp;
  small
    '  #{@volunteers.count} volunteers
= link_to 'New Committee', new_committee_path if current_user.try(:admin?)
|  |&nbsp;
= params[:unassigned] == 'true' ? "Show Unassigned" : link_to('Show Unassigned', :unassigned => true)
|  |&nbsp;
= params[:show_all] == 'true' ? "Show All" : link_to('Show all', :show_all => true)
hr
= render partial: 'volunteers_table'

app/views/committees/new.html.erb
<h1>New committee</h1>

<%= render 'form' %>

<%= link_to '<span class="glyphicon glyphicon-list"></span>'.html_safe, committees_path %>

app/views/committees/show.html.slim
p#notice = notice
h2
  | #{@committee.name} Volunteer Info
  | &nbsp;
  small
    | #{@volunteers.count} Volunteers
  | &nbsp;
  = link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_committee_path(@committee), :class => 'btn btn-xs' if current_user.try(:admin?)
  | &nbsp;
  = link_to '<span class="glyphicon glyphicon-list"></span>'.html_safe, committees_path, :class => 'btn btn-xs'
= params[:show_all] == 'true' ? "Show All" : link_to('Show all', :show_all => true)
hr
- unless emails_for(@volunteers).blank?
  = mail_to emails_for(@volunteers), '<span class="btn btn-primary glyphicon glyphicon-envelope"> email all</span>'.html_safe, :class => 'btn btn-xs'
  br
  br

= render partial: 'volunteers_table'

app/views/committees/show_day.html.slim
p#notice = notice
h2
  | #{@day.titlecase} Schedule
hr
table#data_table.table.table-striped
  thead
    tr
      th Last Name
      th First Name
      th Check In
      th Job
      th Committees
      th Avail
      th Time
      th sort time
      th Hole
      th sort hole

  tbody#js-show-day
    - @volunteers.each do |volunteer|
      tr
        td = link_to(volunteer.last_name, volunteer)
        td = link_to(volunteer.first_name, volunteer)
        - if @read_write
          td
            = check_box_tag "#{@day}_checkin",
               1,
               !!volunteer.send("#{@day}_checkin"),
               class: 'js-check-in',
               data: { url: check_in_volunteer_path(volunteer), day: @day }
            | &nbsp;&nbsp;
            = fa_icon('check', class: 'text-success hidden js-success')
            = fa_icon('times', class: 'text-danger hidden js-fail')
          td = editable(volunteer,
                        "#{@day}_job_id",
                        type: "select",
                        source: Job.all.collect{ |j| { text: j.title, value: j.id } },
                       )
        - else
          td = volunteer.send("#{@day}_checkin") ? fa_icon('check', class: 'text-success') : ''
          td = Job.find_by(id: volunteer.send("#{@day}_job_id")).try(:title)
        td = committees_for(volunteer)
        td = volunteer.send(@day)
        - if @read_write
          td = editable(volunteer,
                        "#{@day}_time",
                        type: "select",
                        source: Volunteer.time_options,
                       )
          td = volunteer.time_option_index_for(@day)
          td = editable(volunteer,
                        "#{@day}_hole",
                        tpl: '<input type="number" max=19 min=0>',
                       )
          td = volunteer.send("#{@day}_hole")
        - else
          td = volunteer.send("#{@day}_time")
          td = volunteer.time_option_index_for(@day)
          td = volunteer.send("#{@day}_hole")
          td = volunteer.send("#{@day}_hole")
javascript:
  $(document).ready(function() {
    $('#data_table').dataTable( {
      "scrollX": true,
      "iDisplayLength": 100,
      'columnDefs': [
        { 'orderData':[7], 'targets': [6] },
        { 'orderData':[9], 'targets': [8] },
        {
          'targets': [7, 9],
          'visible': false,
          'searchable': false
        },
      ]
    });
  });
  StoneyPoint.InlineEditing.init()

app/views/committees/show_jobs.html.slim
p#notice = notice
h2
  | #{@committee ? @committee.name : "All"} Jobs
hr
table#data_table.table.table-striped
  thead
    tr
      th
      th
      th
      th.day-header colspan="3" Thursday
      th.day-header colspan="3" Friday
      th.day-header colspan="3" Saturday
      th.day-header colspan="3" Sunday
    tr
      th Last Name
      th First Name
      th Job
      - 4.times do
        th Avail
        th Time
        th Hole

  tbody
    - @volunteers.each do |volunteer|
      tr
        td = link_to(volunteer.last_name, volunteer)
        td = link_to(volunteer.first_name, volunteer)
        td = volunteer.jobs.pluck(:title).join(", ")
        td = volunteer.thursday
        td
        td
        td = volunteer.friday
        td
        td
        td = volunteer.saturday
        td
        td
        td = volunteer.sunday
        td
        td
= render 'shared/datatable_js'
javascript:

app/views/committees/show_schedule.html.slim
p#notice = notice
h2
  | #{@committee ? @committee.name : "All Committees"} Schedule
hr
table#data_table.table.table-striped
  thead
    tr
      th
      th
      - unless @committee
        th
      - @days.each do |day|
        th.day-header colspan="6" = day.titlecase
    tr
      th Last Name
      th First Name
      - unless @committee
        th Committees
      - @days.each do |day|
        th Avail
        th Job
        th Time
        th sort time
        th Hole
        th sort hole

  tbody#schedule
    - @volunteers.each do |volunteer|
      tr
        td = link_to(volunteer.last_name, volunteer)
        td = link_to(volunteer.first_name, volunteer)
        - unless @committee
          td = committees_for(volunteer)
        - @days.each do |day|
          td = volunteer.send(day)

          - if @read_write
            td = editable(volunteer,
                          "#{day}_job_id",
                          type: "select",
                          source: @job_options,
                          )
            td = editable(volunteer,
                          "#{day}_time",
                          type: "select",
                          source: Volunteer.time_options,
                         )
            td = volunteer.time_option_index_for(day)
            td = editable(volunteer,
                          "#{day}_hole",
                          tpl: '<input type="number" max=19 min=0>',
                         )
            td = volunteer.send("#{day}_hole")

          - else
            td = volunteer.send("#{day}_job").try(:title)
            td = volunteer.send("#{day}_time")
            td = volunteer.time_option_index_for(day)
            td = volunteer.send("#{day}_hole")
            td = volunteer.send("#{day}_hole")

javascript:
  var committee = #{ @committee.present? };
  if(committee) {
    $(document).ready(function() {
      $('#data_table').dataTable( {
        "scrollX": true,
        "iDisplayLength": 100,
        'columnDefs': [
          { 'orderData':[5],  'targets': [4] },
          { 'orderData':[7],  'targets': [6] },
          { 'orderData':[11],  'targets': [10] },
          { 'orderData':[13],  'targets': [12] },
          { 'orderData':[17], 'targets': [16] },
          { 'orderData':[19], 'targets': [18] },
          { 'orderData':[23], 'targets': [22] },
          { 'orderData':[25], 'targets': [24] },
          {
            'targets': [5, 7, 11, 13, 17, 19, 23, 25],
            'visible': false,
            'searchable': false
          },
        ]
      });
    });
  } else {
    $(document).ready(function() {
      $('#data_table').dataTable( {
        "scrollX": true,
        "iDisplayLength": 100,
        'columnDefs': [
          { 'orderData':[6],  'targets': [5] },
          { 'orderData':[8],  'targets': [7] },
          { 'orderData':[12], 'targets': [11] },
          { 'orderData':[14], 'targets': [13] },
          { 'orderData':[18], 'targets': [17] },
          { 'orderData':[20], 'targets': [19] },
          { 'orderData':[24], 'targets': [23] },
          { 'orderData':[26], 'targets': [25] },
          {
            'targets': [6, 8, 12, 14, 18, 20, 24, 26],
            'visible': false,
            'searchable': false
          },
        ]
      });
    });
  }
  StoneyPoint.InlineEditing.init()