config/routes.rb
StoneyPoint::Application.routes.draw do
  devise_for :users
  resources :organizations
  resources :users, only: [:index, :update]

  resources :work_days

  resources :housings do
    member do
      post "/waiver_check", to: "housings#waiver_check"
    end
  end

  resources :caddies

  resources :golfers do
    member do
      post "/waiver_check", to: "golfers#waiver_check"
    end
  end

  resources :jobs

  resources :shifts

  get "/volunteers", to: "committees#index"

  resources :committees do
    collection do
      get "show_all_schedules", to: "committees#show_all_schedules"
      get "show_day", to: "committees#show_day"
    end
    member do
      get "show_schedule", to: "committees#show_schedule"
    end
  end

  resources :volunteers do
    member do
      put "/check_in", to: "volunteers#check_in"
    end
  end

  get "jr_clinic_day", to: "volunteers#jr_clinic_day"
  get "/volunteer_addresses", to: "volunteers#addresses"
  post "/update_shirt_paid", to: "volunteers#update_shirt_paid"

  get "/people/links", to: "people#links", as: 'links'

  resources :people

  get "/welcome_volunteers/welcome", to: "welcome_volunteers#welcome"

  get "/welcome_volunteers/returning", to: "welcome_volunteers#returning"
  post "/welcome_volunteers/find", to: "welcome_volunteers#find"
  get "/welcome_volunteers/thank_you", to: "welcome_volunteers#thank_you"

  get "/welcome_housing/returning", to: "welcome_housing#returning"
  post "/welcome_housing/find", to: "welcome_housing#find"

  get "/welcome_caddies/returning", to: "welcome_caddies#returning"
  post "/welcome_caddies/find", to: "welcome_caddies#find"

  resources :welcome_volunteers, except: [:index, :show]
  resources :welcome_housing, except: [:index, :show]

  get "/welcome_caddies/thank_you", to: "welcome_caddies#thank_you"
  resources :welcome_caddies, except: [:index, :show]

  post "/add_volunteer_committee", to: "volunteers#add_committee", as: 'add_volunteer_committee'
  post "/add_volunteer_job", to: "volunteers#add_job", as: 'add_volunteer_job'
  post "/add_volunteer_shift", to: "volunteers#add_shift", as: 'add_volunteer_shift'
  post "/duplicate_volunteer", to: "volunteers#duplicate", as: 'duplicate_volunteer'
  post "/add_golfer_caddie", to: "golfers#add_caddie", as: 'add_golfer_caddie'
  post "/add_volunteer_organization", to: "volunteers#add_organization", as: 'add_volunteer_organization'
  post "/add_caddie_organization", to: "caddies#add_organization", as: 'add_caddie_organization'
  post "/add_volunteer_housing", to: "volunteers#add_housing", as: 'add_volunteer_housing'
  post "/add_golfer_to_housing", to: "housings#add_golfer", as: 'add_golfer_to_housing'

  get "/shirts", to: "volunteers#shirts", as: 'shirts'

  root :to => 'committees#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :people
  has_many :caddies

  default_scope { order('name ASC') }
  SCHOOL = 'College'

  def self.college_organization_id
    find_by_name(SCHOOL).try(:id)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      redirect_to :back, notice: 'Organization was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name)
    end
end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization, html: {class: 'form-vertical' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, @organization, :class => 'btn btn-small' %>
<%= link_to '<span class="glyphicon glyphicon-list"></span>'.html_safe, organizations_path, :class => 'btn btn-small' %>

app/views/organizations/index.html.erb
<h1>Organizations</h1>
<hr>
<table class ='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <% if current_user.try(:admin?) %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= link_to organization.name, organization %></td>
        <% if current_user.try(:admin?) %>
          <td><%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_organization_path(organization), :class => 'btn btn-small' %></td>
          <td><%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, organization, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-small' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path if current_user.try(:admin?) %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_organization_path(@organization), :class => 'btn btn-small' if current_user.try(:admin?) %>
<%= link_to '<span class="glyphicon glyphicon-list"></span>'.html_safe, organizations_path, :class => 'btn btn-small' %>